version: "3.3"

services:
  portainer:
    image: portainer/portainer-ce:2.11.0-alpine
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/ssd-1tb/docker/portainer:/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`portainer.patz.app`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=patz.app"
      - "traefik.http.routers.frontend.tls.domains[0].main=patz.app"
      - "traefik.http.routers.frontend.tls.domains[0].sans=portainer.patz.app"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"

networks:
  auth_internal:
    external: true
  traefik:
    external:
      name: traefik

